server:
  port: 8091

# H2 db set
spring:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
  datasource:
    url: jdbc:h2:mem:testdb

## RabbitMQ config
multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved