server:
  port: 8091

# H2 db set
spring:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
  datasource:
    url: jdbc:h2:mem:gamification

## RabbitMQ 설정
multiplication:
  exchange: multiplication_exchange
  solved:
    key:  multiplication.solved
  queue: gamification_multiplication_queue
  anything:
    routing-key: multiplication.*

multiplicationHost: http://localhost:8090
